In [2]:
import numpy as np
from numpy import linalg as LA

In [124]:
a=np.array([[1,0,0],
            [0,1,0],
            [0,0,1]])
b=np.array([[1,1,-1],
            [-2,1,0],
            [1,1,1]])

In [133]:
def eulerangles(x,string):
    #euler angles "x-convection" based on cartesian local system
    SMALL=1e-16
    #Xl = Z1 x Z
    #normalizing
    x=np.array([[x[0,0]/LA.norm(x[:,0]),x[0,1]/LA.norm(x[:,1]),x[0,2]/LA.norm(x[:,2])],
                [x[1,0]/LA.norm(x[:,0]),x[1,1]/LA.norm(x[:,1]),x[1,2]/LA.norm(x[:,2])],
                [x[2,0]/LA.norm(x[:,0]),x[2,1]/LA.norm(x[:,1]),x[2,2]/LA.norm(x[:,2])]])
    Xl=np.array([x[1,2],-x[0,2],0])
    #X1’x = X’·X1 = X’x ·X1x + X’y ·X1y + X’z ·X1z = Z1y ·X1x – Z1x ·X1y
    X1lx=np.einsum('i,i->', Xl, x[:,0])
    X1ly=np.einsum('i,i->', Xl, x[:,1])
    Z1xy=np.array([x[0,2],x[1,2],0])
    Z1xy=LA.norm(Z1xy)
    if Z1xy>SMALL:
        alpha=np.arctan2(X1ly, X1lx)
        beta=np.arctan2(Z1xy,x[2,2])
        gamma=-1.*np.arctan2(-x[0,2],x[1,2])
    else:
        alpha=0.
        if np.abs(x[2,2])>SMALL:
            beta=0.
        else:
            beta=np.pi
        gamma=-1.*np.arctan2(X1ly, X1lx)
    if string=='graus':
        return np.array([alpha,beta,gamma])*360/(2*np.pi)
    else:
        return np.array([alpha,beta,gamma])
def eulerrotations(alfa,beta,gamma,base):
    A=np.array([[np.cos(alfa),np.sin(alfa),0],[-np.sin(alfa),np.cos(alfa),0],[0,0,1]])
    B=np.array([[1,0,0],[0,np.cos(beta),np.sin(beta)],[0,-np.sin(beta),np.cos(beta)]])
    C=np.array([[np.cos(gamma),np.sin(gamma),0],[-np.sin(gamma),np.cos(gamma),0],[0,0,1]])
    CB=np.einsum('ij,jk->ik', C, B)
    CBA=np.einsum('ij,jk->ik', CB, A)
    QBase=np.einsum('ij,jk->ik', CBA, base)
    return QBase

In [134]:
eulerangles(b,'graus')

array([ 144.73561032,   45.        ,  -90.        ])

In [135]:
eulerrotations(eulerangles(b,'rad')[0],eulerangles(b,'rad')[1],eulerangles(b,'rad')[2],a)

array([[  4.08248290e-01,   5.77350269e-01,  -7.07106781e-01],
       [ -8.16496581e-01,   5.77350269e-01,   4.32978028e-17],
       [  4.08248290e-01,   5.77350269e-01,   7.07106781e-01]])

In [136]:
eulerrotations(np.pi/4,np.pi/4,np.pi/4,a)

array([[ 0.14644661,  0.85355339,  0.5       ],
       [-0.85355339, -0.14644661,  0.5       ],
       [ 0.5       , -0.5       ,  0.70710678]])